alias fishrc '$EDITOR $HOME/.config/fish/config.fish'
alias oc 'opencode'
alias lg 'lazygit'
alias ldc 'lazydocker'
alias gs 'git status'
alias gp 'git push'
alias gpf 'git push --force'
alias gpft 'git push --follow-tags'
alias gpl 'git pull --rebase'
alias gcl 'git clone'
alias gst 'git stash'
alias grm 'git rm'
alias gmv 'git mv'
alias main 'git checkout main'
alias gco 'git checkout'
alias gcob 'git checkout -b'
alias gb 'git branch'
alias gbd 'git branch -d'
alias grb 'git rebase'
alias grbom 'git rebase origin/master'
alias grbc 'git rebase --continue'
alias gl 'git log'
alias glo 'git log --oneline --graph'
alias grh 'git reset HEAD'
alias grh1 'git reset HEAD~1'
alias ga 'git add'
alias gA 'git add -A'
alias gc 'git commit'
alias gcm 'git commit -m'
alias gca 'git commit -a'
alias gcam 'git add -A; and git commit -m'
alias gfrb 'git fetch origin; and git rebase origin/master'
alias gxn 'git clean -dn'
alias gx 'git clean -df'
alias ghci 'gh run list -L 1'
