palette = "cloudflare_dark"
add_newline = false

[gcloud]
disabled = true

[directory]
style = "fg:sapphire"
truncation_symbol = ""
read_only_style = "fg:red"

[git_branch]
style = "fg:peach"

[git_status]
style = "fg:red"

[character]
success_symbol = "[❯](fg:peach)"
error_symbol = "[❯](fg:red)"
vimcmd_symbol = "[❮](fg:peach)"

[palettes.cloudflare_dark]
rosewater = "#ffc08a"
flamingo = "#ffb37a"
pink = "#ffab66"
mauve = "#ffa252"
red = "#ff9940"
maroon = "#f68a2c"
peach = "#f48120"
yellow = "#ffb04d"
green = "#ff9c52"
teal = "#f28f3b"
sky = "#f48120"
sapphire = "#ff8a1f"
blue = "#ff9c52"
lavender = "#ffb366"
text = "#ffffff"
subtext1 = "#d6d6d6"
subtext0 = "#b5b5b5"
overlay2 = "#8c8c8c"
overlay1 = "#666666"
overlay0 = "#404040"
surface2 = "#262626"
surface1 = "#1a1a1a"
surface0 = "#101010"
base = "#050505"
mantle = "#000000"
crust = "#000000"
