# Cloudflare light palette

$rosewater = rgb(ffc08a)
$rosewaterAlpha = ffc08a

$flamingo = rgb(ffb37a)
$flamingoAlpha = ffb37a

$pink = rgb(ffab66)
$pinkAlpha = ffab66

$mauve = rgb(ffa252)
$mauveAlpha = ffa252

$red = rgb(e96a00)
$redAlpha = e96a00

$maroon = rgb(f48120)
$maroonAlpha = f48120

$peach = rgb(f48120)
$peachAlpha = f48120

$yellow = rgb(cc8400)
$yellowAlpha = cc8400

$green = rgb(ff9c52)
$greenAlpha = ff9c52

$teal = rgb(ff934f)
$tealAlpha = ff934f

$sky = rgb(f48120)
$skyAlpha = f48120

$sapphire = rgb(e67300)
$sapphireAlpha = e67300

$blue = rgb(d96d00)
$blueAlpha = d96d00

$lavender = rgb(ffb04d)
$lavenderAlpha = ffb04d

$text = rgb(161616)
$textAlpha = 161616

$subtext1 = rgb(3e3e3e)
$subtext1Alpha = 3e3e3e

$subtext0 = rgb(5c5c5c)
$subtext0Alpha = 5c5c5c

$overlay2 = rgb(7a7a7a)
$overlay2Alpha = 7a7a7a

$overlay1 = rgb(9a9a9a)
$overlay1Alpha = 9a9a9a

$overlay0 = rgb(c4c4c4)
$overlay0Alpha = c4c4c4

$surface2 = rgb(d9d9d9)
$surface2Alpha = d9d9d9

$surface1 = rgb(ececec)
$surface1Alpha = ececec

$surface0 = rgb(ffffff)
$surface0Alpha = ffffff

$base = rgb(fafafa)
$baseAlpha = fafafa

$mantle = rgb(f1f1f1)
$mantleAlpha = f1f1f1

$crust = rgb(e8e8e8)
$crustAlpha = e8e8e8
